# Intro to NumPy

In [1]:
import numpy as np

## 1. DataTypes

- NumPy's main datatype is **ndarray**
    - This type applies to numpy arrays of any dimension
    
### Ndarray Attributes

- ndim – dimension count
- shape – num elements in each sub-dimension
- size – element count
- dtype – type of data stored

In [6]:
arr_1d = np.array([1, 2, 3]) # Shape = (1,3)
arr_1d

array([1, 2, 3])

In [11]:
arr_2d = np.array([[1, 2.0, 3.3],
                   [4, 5, 6.5]]) # Shape = (2,3)

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [1, 2, 3]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18],
                    [10, 11, 12]]]) # Shape = (2,4,3)

In [17]:
type(arr_1d), type(arr_3d)

(numpy.ndarray, numpy.ndarray)

In [7]:
arr_1d.shape

(3,)

In [12]:
arr_3d.shape

(2, 4, 3)

In [14]:
arr_1d.ndim, arr_2d.ndim

(1, 2)

In [16]:
arr_1d.size, arr_2d.size, arr_3d.size

(3, 6, 24)

In [15]:
arr_2d.dtype, arr_3d.dtype

(dtype('float64'), dtype('int32'))

## 2. Creating Arrays

### Basics

#### np.ones(shape, dtype=None)
- Return a new array of given shape & type, filled with ones
    
#### np.zeroes(shape, dtype=None)
- Return a new array of given shape & type, filled with zeroes

#### np.arange(\[start,\] stop\[, step,\], dtype=None)
- Return evenly spaced values within a given interval
- `stop` is exclusive

In [27]:
ones = np.ones((2, 3), dtype='int32')
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
type(ones), ones.dtype

(numpy.ndarray, dtype('int32'))

In [29]:
arr_range = np.arange(0, 10, 2)
arr_range

array([0, 2, 4, 6, 8])

### Random Numbers

#### np.random.randint(low, high=None, size=None, dtype='l')
- Return random integers from `low` (inc) to `high` (exc)
- `size` means shape
- `low` param is optional, default 0

#### np.random.random(size=None)
- Return random floats in the half-open interval `[0.0, 0.1)`

#### np.random.rand(d0, d1, ..., dn)
- Return random values in a given shape

In [30]:
arr_rand = np.random.randint(0, 10, size=(3, 5))
arr_rand

array([[5, 6, 2, 6, 8],
       [3, 2, 0, 4, 7],
       [7, 1, 0, 4, 4]])

In [33]:
"Elements: " + str(arr_rand.size), "Shape: " + str(arr_rand.shape)

('Elements: 15', 'Shape: (3, 5)')

In [34]:
arr_rand2 = np.random.random((4,2))
arr_rand2

array([[0.12168463, 0.20612932],
       [0.65245851, 0.1902626 ],
       [0.03445084, 0.0842392 ],
       [0.8776608 , 0.07245298]])

In [35]:
arr_rand3 = np.random.rand(4,2)
arr_rand3

array([[0.09428003, 0.39954593],
       [0.41129143, 0.57502195],
       [0.31167425, 0.92525884],
       [0.02600328, 0.12513635]])

### Random Seed

#### np.random.seed(seed=None)
- A seed allows reproducible randomness, useful when sharing the notebook
- A defined seed only applies to the cell its declared in

In [44]:
np.random.seed(42)
arr_rand4 = np.random.randint(21, size=(2,10))
arr_rand4

array([[ 6, 19, 14, 10,  7, 20,  6, 18, 10, 10],
       [20,  3,  7,  2, 20,  1, 11,  5,  1, 20]])

## 3. Viewing Arrays & Matrices

**Matrix** – an array with 2+ dimensions

Access matrix elements by index via square brackets, e.g. `arr[d0, d1]`

#### np.unique(ndarray)
- Return the unique elements as a (sorted?) array
- Works on ndarray of any shape



In [45]:
np.unique(arr_rand4)

array([ 1,  2,  3,  5,  6,  7, 10, 11, 14, 18, 19, 20])

In [48]:
arr_3d, arr_3d[0,2,1]

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [ 1,  2,  3]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18],
         [10, 11, 12]]]),
 8)

In [47]:
arr_rand4[1], arr_rand4[1,4]

(array([20,  3,  7,  2, 20,  1, 11,  5,  1, 20]), 20)

In [49]:
arr_3d[:2, 1:3, 1:] # Slicing also works on ndarrays

array([[[ 5,  6],
        [ 8,  9]],

       [[14, 15],
        [17, 18]]])

In [50]:
arr_rand5 = np.random.randint(10, size=(2,3,4,5))
arr_rand5

array([[[[0, 9, 5, 8, 0],
         [9, 2, 6, 3, 8],
         [2, 4, 2, 6, 4],
         [8, 6, 1, 3, 8]],

        [[1, 9, 8, 9, 4],
         [1, 3, 6, 7, 2],
         [0, 3, 1, 7, 3],
         [1, 5, 5, 9, 3]],

        [[5, 1, 9, 1, 9],
         [3, 7, 6, 8, 7],
         [4, 1, 4, 7, 9],
         [8, 8, 0, 8, 6]]],


       [[[8, 7, 0, 7, 7],
         [2, 0, 7, 2, 2],
         [0, 4, 9, 6, 9],
         [8, 6, 8, 7, 1]],

        [[0, 6, 6, 7, 4],
         [2, 7, 5, 2, 0],
         [2, 4, 2, 0, 4],
         [9, 6, 6, 8, 9]],

        [[9, 2, 6, 0, 3],
         [3, 4, 6, 6, 3],
         [6, 2, 5, 1, 9],
         [8, 4, 5, 3, 9]]]])

### How would we get the center 3 numbers of the innermost arrays?

In [54]:
arr_rand5[:, :, :, 1:4]

array([[[[9, 5, 8],
         [2, 6, 3],
         [4, 2, 6],
         [6, 1, 3]],

        [[9, 8, 9],
         [3, 6, 7],
         [3, 1, 7],
         [5, 5, 9]],

        [[1, 9, 1],
         [7, 6, 8],
         [1, 4, 7],
         [8, 0, 8]]],


       [[[7, 0, 7],
         [0, 7, 2],
         [4, 9, 6],
         [6, 8, 7]],

        [[6, 6, 7],
         [7, 5, 2],
         [4, 2, 0],
         [6, 6, 8]],

        [[2, 6, 0],
         [4, 6, 6],
         [2, 5, 1],
         [4, 5, 3]]]])